# Generated by Django 4.2.30 on 2026-06-10 13:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('CASH', 'Efectivo'), ('BANK', 'Banco'), ('WALLET', 'Billetera virtual'), ('INVESTMENT', 'Inversion'), ('FOREIGN_CURRENCY', 'Moneda extranjera'), ('OTHER', 'Otro')], max_length=30)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], default='ARS', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('VOIDED', 'Anulada')], default='CONFIRMED', max_length=20)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='cashflow.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='cashflow.account')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_invoice', models.DateField(blank=True, null=True)),
                ('date_payment', models.DateField()),
                ('description', models.CharField(max_length=240)),
                ('voucher_number', models.CharField(blank=True, max_length=80)),
                ('movement_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso'), ('TRANSFER_IN', 'Transferencia entrante'), ('TRANSFER_OUT', 'Transferencia saliente'), ('ADJUSTMENT', 'Ajuste')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('VOIDED', 'Anulado')], default='CONFIRMED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('void_reason', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='cashflow.account')),
            ],
            options={
                'ordering': ['-date_payment', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyCashCloseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('Cerrado', 'Closed')], default='OPEN', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('document_number', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name', 'document_number')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('DONE', 'Realizado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='cashflow.client')),
            ],
            options={
                'ordering': ['-event_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MovementCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('movement_type', models.CharField(choices=[('INCOME', 'Ingreso'), ('EXPENSE', 'Egreso'), ('TRANSFER', 'Transferencia'), ('ADJUSTMENT', 'Ajuste')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('requires_provider', models.BooleanField(default=False)),
                ('requires_employee', models.BooleanField(default=False)),
                ('requires_tax', models.BooleanField(default=False)),
                ('requires_event', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(blank=True, max_length=80)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_payments', to='cashflow.account')),
                ('cash_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_payment_record', to='cashflow.cashmovement')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cashflow.taxtype')),
            ],
            options={
                'ordering': ['-payment_date', 'tax_type'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('remind_before_days', models.PositiveIntegerField(default=0)),
                ('recurrence_type', models.CharField(choices=[('NONE', 'Sin recurrencia'), ('MONTHLY', 'Mensual'), ('BIMONTHLY', 'Bimestral'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual'), ('CUSTOM_DAYS', 'Dias personalizados')], default='NONE', max_length=20)),
                ('custom_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DONE', 'Hecho'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='cashflow.event')),
                ('related_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='cashflow.provider')),
                ('related_tax_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='cashflow.taxpayment')),
            ],
            options={
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProviderLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('DEBT', 'Deuda'), ('PAYMENT', 'Pago'), ('ADJUSTMENT', 'Ajuste')], max_length=20)),
                ('description', models.CharField(max_length=240)),
                ('document_number', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.TextField(blank=True)),
                ('cash_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_ledger_entry', to='cashflow.cashmovement')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_ledger_entries', to='cashflow.event')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='cashflow.provider')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('extra_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PLANNED', 'Planificado'), ('WORKED', 'Trabajado'), ('PARTIALLY_PAID', 'Parcialmente pagado'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cashflow.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='cashflow.event')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cashflow.employeerole')),
            ],
            options={
                'ordering': ['-work_date', 'event', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cashflow.eventstaffassignment')),
                ('cash_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payment', to='cashflow.cashmovement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cashflow.employee')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_payments', to='cashflow.event')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='cashflow.movementcode'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='cashflow.employee'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='cashflow.event'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='cashflow.provider'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='tax_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='cashflow.taxpayment'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='cashflow.accounttransfer'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyAccountClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_transfer_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_transfer_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('calculated_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('declared_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_closes', to='cashflow.account')),
                ('close_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_closes', to='cashflow.dailycashclosegroup')),
            ],
            options={
                'ordering': ['close_group__date', 'account__name'],
                'unique_together': {('close_group', 'account')},
            },
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['date_payment', 'account'], name='cashflow_ca_date_pa_37c52a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['status', 'movement_type'], name='cashflow_ca_status_63f7b3_idx'),
        ),
    ]
