# Generated by Codex on 2026-06-28

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cashflow", "0003_eventbudget_eventbudgetitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventBudgetPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idempotency_key", models.CharField(default=uuid.uuid4, max_length=120, unique=True)),
                ("mp_preference_id", models.CharField(blank=True, max_length=100)),
                ("preference_init_point", models.URLField(blank=True, max_length=1000)),
                ("preference_sandbox_init_point", models.URLField(blank=True, max_length=1000)),
                ("mp_payment_id", models.CharField(blank=True, max_length=100)),
                ("mp_merchant_order_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                            ("in_process", "En proceso"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_detail", models.CharField(blank=True, max_length=100)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("payment_type", models.CharField(blank=True, max_length=50)),
                ("installments", models.PositiveIntegerField(default=1)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="ARS", max_length=3)),
                ("budget", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="cashflow.eventbudget")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventBudgetPaymentWebhookLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mp_notification_id", models.CharField(max_length=100)),
                ("deduplication_key", models.CharField(max_length=64, unique=True)),
                ("topic", models.CharField(max_length=50)),
                ("payload", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="eventbudgetpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("mp_preference_id", ""), _negated=True),
                fields=("mp_preference_id",),
                name="unique_event_budget_mp_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventbudgetpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("mp_payment_id", ""), _negated=True),
                fields=("mp_payment_id",),
                name="unique_event_budget_mp_payment",
            ),
        ),
    ]
