# Generated by Codex on 2026-06-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cashflow", "0004_eventbudgetpayment_webhooklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventbudgetpayment",
            name="cash_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_budget_payment",
                to="cashflow.cashmovement",
            ),
        ),
    ]
