# Generated by Django 4.2.30 on 2026-07-07 01:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_eventbudgetpayment_cash_movement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GraduationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_ticket', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['event__event_date', 'event__name'],
            },
        ),
        migrations.CreateModel(
            name='TicketPurchaseWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_notification_id', models.CharField(max_length=100)),
                ('deduplication_key', models.CharField(max_length=64, unique=True)),
                ('topic', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='function_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sketch',
            field=models.FileField(blank=True, upload_to='event-sketches/'),
        ),
        migrations.AddField(
            model_name='eventbudgetpayment',
            name='budget_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cashflow.eventbudgetitem'),
        ),
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('email', models.EmailField(max_length=254)),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=120, unique=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=100)),
                ('preference_init_point', models.URLField(blank=True, max_length=1000)),
                ('preference_sandbox_init_point', models.URLField(blank=True, max_length=1000)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_process', 'En proceso'), ('paid', 'Pagado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('cash_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_purchase', to='cashflow.cashmovement')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_purchases', to='cashflow.graduate')),
                ('graduation_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='cashflow.graduationevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='graduationevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='graduation', to='cashflow.event'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='graduation_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduates', to='cashflow.graduationevent'),
        ),
        migrations.AddConstraint(
            model_name='ticketpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('mp_preference_id', ''), _negated=True), fields=('mp_preference_id',), name='unique_ticket_purchase_mp_preference'),
        ),
        migrations.AddConstraint(
            model_name='ticketpurchase',
            constraint=models.UniqueConstraint(condition=models.Q(('mp_payment_id', ''), _negated=True), fields=('mp_payment_id',), name='unique_ticket_purchase_mp_payment'),
        ),
        migrations.AlterUniqueTogether(
            name='graduate',
            unique_together={('graduation_event', 'first_name', 'last_name')},
        ),
    ]
