# Generated by Django 4.2.30 on 2026-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_event_360_payment_token_close_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationticketprice',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
